# Generated by Django 4.2.11 on 2025-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Class')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
    ]
