# Generated by Django 5.1.6 on 2025-03-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_classroom_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Area'),
        ),
    ]
